### ISSUE TITLE
Notifications panels not turning dark

### ISSUE THREAD

**Issue by sabeehsha** [davidtrpcevski/Advanced-LineageOS-Releases#2]
I have the screenshot
![Screenshot_20191204-225127_Chrome](https://user-images.githubusercontent.com/44654690/70166814-7b4d2380-16eb-11ea-85bb-8a2b3ad59b85.png)

**Comment by davidtrpchevski** [comment]
Hi,

The notifications are by default white as in AOSP and LineageOS sources. Not an issue. I will try to adapt the notifications to match the theme in future releases.
