### ISSUE TITLE
Email Apps keep crashing with LineageOS 16.0 20191206 Release

### ISSUE THREAD

**Issue by RITFW** [davidtrpcevski/Advanced-LineageOS-Releases#3]
i installed the _LineageOS 16.0 20191205 Release_ over the previous version with a dirty flash. I know a clean flash is always recommended, but it is always a hassle to set up everything again and usually it always worked with dirty flashes coming from the same version. If a clean flash will solve my problem I am happy to do so.

After the last Update to the _LineageOS 16.0 20191205 Release_ every email client starts crashing once I start using it. It happens with the latest GitHub FairEmail release, with the latest F-Droid K-9 Mail release as well with the built in email client. When I try to set up an email client in the settings -> accounts section I cannot find K-9 Mail nor FairEmail. 

Is this behavior a bug with the latest build and can be fixed in upcoming releases? I really like the ROM and I would be happy to have a working email client again to make full use of my phone. 

Rom Version: LineageOS 16.0 20191206 Release
No GApps installed
RAM: 4GB
Storage: 64 GB
Firmware: V11.0.2.0.NCFMIXM_83170d3e3a_7.0
Email provider: posteo.de/en

I am happy to provide any other logs or do some testing if that can be of any help. Thanks a lot for building and I hope it can be fixed.

**Comment by davidtrpchevski** [comment]
Hi,

I have tried hard to find the cause of the issue that you have, but unfortunately I cannot get these applications to crash. I have installed and set up account on each of them, but they all work fine. I did few screenshots so that you can be assured that it's all working fine. In the future let the OTA Updater do it's job since I have never had problems with it.

https://imgur.com/gallery/8ZDx77y

**Comment by davidtrpchevski** [comment]
Issue has been confirmed and it is caused by Google's latest security patch. Me and the LineageOS team have confirmed and a fix has been pushed to LineageOS gerrit. The next release will have the patch implemented. Sorry for inconvenience.

**Comment by RITFW** [comment]
Thank you so much for the respond and all the effort in solving the problem. I am happy when I know that it will be fixed in an upcoming release. Software can't always be bug free and I am happy that there will be a patch available soon. Keep on your great work!

**Comment by davidtrpchevski** [comment]
Please confirm if the issue is fixed in the new release. If it is, please feel free to close this issue.

**Comment by RITFW** [comment]
I installed the _LineageOS 16.0 20191208 Release_ and FairEmail and K-9 Mail work perfectly again. Thank you so much for your effort in fixing the problem and providing a new build in such a short time. I highly appreciate it!
