### ISSUE TITLE
The last 2 cores are offline, cannot enable them.

### ISSUE THREAD

**Issue by crok** [davidtrpcevski/Advanced-LineageOS-Releases#5]
**Describe the bug**
The last 2 cores are offline, I cannot enable them.

**To Reproduce**
They are just offline.. I used KA and EXKM to check it, tried to activate them but they are going offline in half a sec.

**Expected behavior**
All 8 cores should be online or at least I should be able to activate them, right?

**Screenshots**
I don't think this is necessary but I will attach it if needed.

**Logs**

[bugreport-lineage_mido-PQ3A.190801.002-2019-12-08-20-39-20](https://mega.nz/#!h9QQHK6R!GJtolALgbJiKnz8lb0t7FTFPdnxIUpEIvWhdRgNSd18)

**Recovery**

> [*] TWRP [_] OrangeFox [_] Other

**Gapps**

> [_] No [*] Yes, a slightly modified OpenGApps Nano (it's basically a Pico + BatteryUsage from Nano, I used to flash Nano with custom .gapps-config)

**Firmware version**
The one derived from MIUI V10.2.3.0 global stable.

**Fingerprint**

> [*] Goodix [_] FPC

**Used filesystems**

> [*] ext4 [_] f2fs

**RAM Variant**

> [_] 2GB [*] 3GB [_] 4GB

> Additional information:
>
> [No] Dirty flash - I'm using lineage-16.0-20191208-mido-signed.zip clean flashed
>
> [No] Xposed
>
> [No] Custom kernel
>
> [No] Performance/Battery enhancements

**Additional context**
Nothing special. I'm using Magisk v20.1 but I don't think it's relevant.

**Comment by davidtrpchevski** [comment]
Hi Crok,

I'm trying hard to get this issue replicated on my mido but unfortunately all cores are working as they should and I cannot see the issue here. If we are talking when the device gets below 15%, the 4 cores are getting disabled by design. Could you please upload kernel log (dmesg)?

**Comment by crok** [comment]
Thank you for the prompt answer!
No, it is not the situation when the SoC restricts the cores while battery is on low voltage (72% at the moment). [dmesg is available here](https://pastebin.com/2CGQpUNx). I rebooted it once again and it's working at the moment.. really strange because I restarted a couple of times already..

**Comment by davidtrpchevski** [comment]
> Thank you for the prompt answer!
> No, it is not the situation when the SoC restricts the cores while battery is on low voltage (72% at the moment). [dmesg is available here](https://pastebin.com/2CGQpUNx). I rebooted it once again and it's working at the moment.. really strange because I restarted a couple of times already..

I would suggest to check if EXKM or KA have any profiles applied. If this issue is solved, then feel free to close this bug report.

**Comment by crok** [comment]
> I would suggest to check if EXKM or KA have any profiles applied. If this issue is solved, then feel free to close this bug report.

KA and EXKM were not even installed (I installed them just to check what's going on since I felt some performance decreasement and saw the reported issue with the cores).

I would like to leave this one open for some days - if you don't mind - and I will close it if it won't came back or grab more logs if it does. Thank you!

**Comment by davidtrpchevski** [comment]
> > I would suggest to check if EXKM or KA have any profiles applied. If this issue is solved, then feel free to close this bug report.
> 
> KA and EXKM were not even installed (I installed them just to check what's going on since I felt some performance decreasement and saw the reported issue with the cores).
> 
> I would like to leave this one open for some days - if you don't mind - and I will close it if it won't came back or grab more logs if it does. Thank you!

Sure, no problem. That's the idea.

**Comment by crok** [comment]
> 
> Sure, no problem. That's the idea.

The issue didn't replicate itself for 3 whole days.

By the way 3 days after I unplugged the charger at 100% the SoT is around 4hrs (light usage pattern, no gaming, etc) and the battery is still at 45% :D Amazing :D

**Comment by davidtrpchevski** [comment]
> > Sure, no problem. That's the idea.
> 
> The issue didn't replicate itself for 3 whole days.
> 
> By the way 3 days after I unplugged the charger at 100% the SoT is around 4hrs (light usage pattern, no gaming, etc) and the battery is still at 45% :D Amazing :D

Happy to hear that. Glad you like it :wink:
