### ISSUE TITLE
E1001: Failed to update system image

### ISSUE THREAD

**Issue by Eithoo** [davidtrpcevski/Advanced-LineageOS-Releases#7]
I tried a few times to flash this ROM, but it always stops at about 70% with error:

```
E1001: Failed to update system image.
Updater process ended with ERROR: 7
Error installing zip file '/sdcard1/lineage-17.1-20200311-mido-signed.zip'
```

**Comment by crok** [comment]
Please post the whole recovery.log
Which custom recovery are you using and which version?
Are you sure your phone is a Mido?

**Comment by Eithoo** [comment]
> Are you sure your phone is a Mido?

100% sure
> Which custom recovery are you using and which version?

TWRP, 3.3.1-0 (checked on 3.3.0-1 too)

> Please post the whole recovery.log

(moment)

**Comment by Eithoo** [comment]
I copied the firmware to SD Card again (via ADB this time), changed the TWRP version to the older one and this time it worked. Apparently earlier the file was copied incorrectly.

**Comment by crok** [comment]
Good to hear (: Probably the log did contain some MTP related entries?

**Comment by Eithoo** [comment]
No idea. I was doing everything again to make the log and send here and this time it worked, so I don't even have log from the that incorrect installation :smile:

**Comment by UltimateSolar** [comment]
in TWRP the user needs to mount ALL storage deviecs (check all checkboxes)

then try to flash zip again :D

or it will fail to flash with this problem E1001

![how-to-get-e-OS-on-Nexus-6P-via-usb-A-to-usb-C-adapter-and-stick_1](https://github.com/Android-Device-Development/LineageOS-Releases/assets/153558313/eee8c55b-9802-4c5f-861a-71d749dae631)
