### ISSUE TITLE
Google Apps

### ISSUE THREAD

**Issue by truefriend-cz** [davidtrpcevski/Advanced-LineageOS-Releases#8]
Please change from Google Apps Full to Google Apps pico. Device is very slowly responses.
Thanks

**Comment by fudoteki** [comment]
for my personal use, GApps Full:
google core frameworks and,
Keyboard using GBoard
Launcher using LawnChair

exclude:
Google TTS
Search
WellBeing
Google Now
PixelLauncher
Calculator (I using Mi Calc)
Tag Google
Books
NewsStand
Music
Movies
PlayGames
TalkBack

may can be references, thank you

**Comment by davidtrpchevski** [comment]
Personal releases. Will not change.
